module.exports = {
    SITE_NAME: "Discord Player",
    NAV_LINKS: [
        { name: "Home", path: "/", external: false },
        { name: "Documentation", path: "/docs", external: false },
        { name: "GitHub", path: "https://github.com/Androz2091/discord-player", external: true },
        { name: "Discord", path: "https://discord.com", external: true },
    ],
    DISCORD_INVITE: "https://discord.com",
    GITHUB_LINK: "https://github.com/Androz2091/discord-player",
    INSTALL_COMMAND: "npm install discord-player",
    DESCRIPTION: "Discord Player is a powerful <b>Node.js</b> module that allows you to easily build <b>Discord.js</b> music bot.",
    FOOTER_DESCRIPTION: "A powerful framework to make discord music bots.",
    STATS: {
        MODULE_NAME: "discord-player",
        GITHUB_REPO: "Androz2091/discord-player"
    },
    META: {
        URL: "https://snowdocs.vercel.app",
        TITLE: "Discord Player",
        DESCRIPTION: "🎧 Complete framework to simplify the implementation of music commands using Discord.js",
        IMAGE: "https://snowdocs.vercel.app/favicon.png"
    },
    DOCUMENTATION_SOURCE: "https://raw.githubusercontent.com/Androz2091/discord-player/docs/v5.json",
    BRANCH: "master",
    PARAMS: {
        string: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String',
        String: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String',
        number: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number',
        Number: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number',
        boolean: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean',
        Boolean: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean',
        symbol: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol',
        Symbol: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol',
        void: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined',
        Object: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object',
        object: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object',
        Function: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function',
        function: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function',
        Array: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array',
        Set: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set',
        Map: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map',
        Date: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date',
        RegExp: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp',
        Promise: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise',
        Error: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error',
        EventEmitter: 'https://nodejs.org/dist/latest/docs/api/events.html#events_class_eventemitter',
        Timeout: 'https://nodejs.org/dist/latest/docs/api/timers.html#timers_class_timeout',
        Buffer: 'https://nodejs.org/dist/latest/docs/api/buffer.html#buffer_class_buffer',
        ReadableStream: 'https://nodejs.org/dist/latest/docs/api/stream.html#stream_class_stream_readable',
        Readable: 'https://nodejs.org/dist/latest/docs/api/stream.html#stream_class_stream_readable',
        ChildProcess: 'https://nodejs.org/dist/latest/docs/api/child_process.html#child_process_class_childprocess',
        Worker: 'https://nodejs.org/api/worker_threads.html#worker_threads_class_worker',
        MessagePort: 'https://nodejs.org/api/worker_threads.html#worker_threads_class_messageport',
        IncomingMessage: 'https://nodejs.org/dist/latest/docs/api/http.html#http_class_http_incomingmessage',
        m3u8Stream: 'https://nodejs.org/dist/latest/docs/api/stream.html#stream_class_stream_readable',
        RequestInfo: 'https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch',
        RequestInit: 'https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch',
        RequestOptions: 'https://nodejs.org/dist/latest/docs/api/http.html#http_http_request_options_callback',
        m3u8Options: 'https://github.com/fent/node-m3u8stream#m3u8streamurl-options',
        CheerioRoot: 'https://cheerio.js.org',
        Response: 'https://developer.mozilla.org/en-US/docs/Web/API/Response',
        '*': 'https://flow.org/en/docs/types/any',
        any: 'https://flow.org/en/docs/types/any',
        DiscordClient: 'https://discord.js.org/#/docs/main/stable/class/Client',
        DiscordCollection: 'https://discord.js.org/#/docs/collection/master/class/Collection',
        DiscordMessage: 'https://discord.js.org/#/docs/main/stable/class/Message',
        DiscordVoiceChannel: 'https://discord.js.org/#/docs/main/stable/class/VoiceChannel',
        DiscordVoiceConnection: 'https://discord.js.org/#/docs/main/stable/class/VoiceConnection',
        DiscordSnowflake: 'https://discord.js.org/#/docs/main/stable/typedef/Snowflake',
        DiscordCollector: 'https://discord.js.org/#/docs/main/stable/class/MessageCollector',
        YTDLDownloadOptions: 'https://github.com/fent/node-ytdl-core#ytdlurl-options',
        DiscordUser: 'https://discord.js.org/#/docs/main/stable/class/User',
        DiscordMessageCollector: 'https://discord.js.org/#/docs/main/stable/class/MessageCollector',
    },
    LOCAL_TYPES: [/* Leave this empty */]
};
